### PR TITLE
fix(ui-library): component toggle-switch fixes

### LINKED ISSUE #505: ToggleSwitch - check if events are missing and add them
#### Description / User Story

The toggle switch should at least have the following events:
- Change
- Focus
- Blur

The events should be implemented similar to how it is currently already done for Checkbox, TextButton and IconButton. You can also see how the events are working in the vanilla js example application.

One finding we had there was that the events can not have the same name as the html events.

Update: 05.04.: It seems that the events are already there, but the Focus and Blur events are firing multiple times when changing / clicking the control/label. This should be fixed.

----
#### Acceptance Criteria
- [x] Change event was implemented
- [x] Focus event was implemented
- [x] Blur event was implemented
- [x] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss cab support here

----
#### Background information
- [Link](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=ksr0Vb) to props documentation (consider All Props page & Component page)

### LINKED ISSUE #792: Toggle Switch - add focus ring to readonly state
#### Description / User Story

Currently the Toggle Switch does not have a focus ring in the readonly state. This should be fixed.

----
#### Acceptance Criteria
- [x] When in readonly state, the Toggle Switch can be focused and when done so a focus ring will appear.

----
#### Background information
- ...

### LINKED ISSUE #793: Toggle Switch - active state has wrong color and state labels have wrong color in disabled & readonly state
#### Description / User Story

Currently the Toggle Switch control has the wrong color in active state and wrong colors applied to the state labels in the disabled & readonly state. As per design, the state labels should have the disabled color when in disabled state. Also the label should still have the default color. It appears that these two are currently switched.

The wrong color of the active state only appear when you click the control or the label, not if you just switch "active" to true.

----
#### Acceptance Criteria
- [x] When in active state, the control of the Toggle Switch has the defined color form design (also when clicking and not only switching checked to true)
- [x] When in disabled state, the state labels of the Toggle Switch have the defined color from design.
- [x] When in disabled state, the label of the Toggle Switch have the defined color from design.
- [x] When in readonly state, the know of the Toggle Switch has the defined color form design
- [x] When in disabled state, the know of the Toggle Switch has the defined color form design

----
#### Background information
- _Add relevant information here_

### LINKED ISSUE #1030: Toggle Switch - add gap between label and hint
### Description / User story

Gap between label and hint is missing and should be added.

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] Gap between Label and Hint is added in code via the defined token form design

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1047: Toggle switch  - component requires two clicks to change the state
### What is affected?

Component

### Description

The state of switch in Toggle switch should swiftly change with single click rather than having to click twice. This does not happen consistently. Also it does only happen when clicking the control, apparently not when clicking the label.

### Steps to reproduce

1. Visit https://b01ler.onrender.com/?path=/docs/components-toggle-switch--docs
2. Try switching the state from unchecked to be checked. Only after two clicks the state will change.

### Affected version(s)

_No response_

### Operating system / Browser / Environment

Chrome browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ashk1996**
closes #1030 
closes #792
closes #505
closes #793
closes #1047

### CODE REVIEW

**Review by thrbnhrtmnn — CHANGES_REQUESTED** [review]
Hey @ashk1996 , thank you for all the fixes, here are my findings:

[#1047](https://github.com/deven-org/boiler/issues/1047):
- The issue seems not to be fixed. It still sometimes requires 2 clicks to change the state

[#793](https://github.com/deven-org/boiler/issues/793):
- The knob color in disabled active is wrong (white), it should be the same as in disabled inactive state (darker grey than control); same for the readonly state; same for dark and light mode
- When changing the state of the toggle via clicking at least once and not via changing "active" to true or false via the controls panel in storybook, the states seem to be stuck and we are not seeing any hover states anymore, at least the inactive state always shows the color for the pressed state and the active state always shows the rest state color (might be fixed by #1047)

No issues found for [#505](https://github.com/deven-org/boiler/issues/505)

No issues found for [#792](https://github.com/deven-org/boiler/issues/792)

No issue found for [#1030](https://github.com/deven-org/boiler/issues/1030)

**Comment by ashk1996** [comment]
> Hey @ashk1996 , thank you for all the fixes, here are my findings:
> 
> [#1047](https://github.com/deven-org/boiler/issues/1047):
> 
> * The issue seems not to be fixed. It still sometimes requires 2 clicks to change the state
> 
> [#793](https://github.com/deven-org/boiler/issues/793):
> 
> * The knob color in disabled active is wrong (white), it should be the same as in disabled inactive state (darker grey than control); same for the readonly state; same for dark and light mode
> * When changing the state of the toggle via clicking at least once and not via changing "active" to true or false via the controls panel in storybook, the states seem to be stuck and we are not seeing any hover states anymore, at least the inactive state always shows the color for the pressed state and the active state always shows the rest state color (might be fixed by [Toggle switch  - component requires two clicks to change the state #1047](https://github.com/deven-org/boiler/issues/1047))
> 
> No issues found for [#505](https://github.com/deven-org/boiler/issues/505)
> 
> No issues found for [#792](https://github.com/deven-org/boiler/issues/792)
> 
> No issue found for [#1030](https://github.com/deven-org/boiler/issues/1030)

Hi @thrbnhrtmnn 

I've fixed the issue for #793. Could you please have a look again.
For issue #1047 could you please send me a screenshot.

Thank you

**Comment by thrbnhrtmnn** [comment]
> Hi @thrbnhrtmnn
> 
> I've fixed the issue for #793. Could you please have a look again. For issue #1047 could you please send me a screenshot.
> 
> Thank you

Hey @ashk1996 , as just discussed, here are the open points that need to be fixed:
- #1047 > the issue is resolved once a single click in the control-wrapper always changes active to true/false (the issue with the events can be fixed in a separate ticket, if this is even something we need to fix)
- #793 > the active and hover state are always correct, but we seem to miss the pressed state completely (at least the background color of the control-wrapper is not displayed); in the end we should also only use the focus ring color from the focus state
- #793 > the background color of the control-wrapper is now wrong in readonly and disabled state

Let me know if you have any more questions or lets have a quick huddle in case something is unclear.

**Review by bar-tay — APPROVED** [review]

**Review by bar-tay — APPROVED** [review]

**Review by thrbnhrtmnn — APPROVED** [review]
Changes all look good! We can merge it :-)

I will create a new ticket though to also add the pressed state and potentially to do a change to the focus state to not overlap with pressed and hover state. This needs to be discussed with design first though.

**Pull request merged**
