### PR TITLE
fix(storybook): checkbox size issue

### LINKED ISSUE #754: Checkbox - fix size issues
#### Description / User Story

The Checkbox control width gets smaller, when the label gets too long.

See:
checkbox-bug

----
#### Requirements
- none

----
#### Acceptance Criteria
- [ ] The Checkbox control does not change in size, regardless how long the label is.
- [ ] If possible: Tests have been added to the Checkbox to prevent these issues from happening again

----
#### Background information
- ...

### PR DESCRIPTION
**Pull request by bar-tay**
closes #754

### CODE REVIEW

**Review by thrbnhrtmnn — APPROVED** [review]
Hey @bar-tay , this looks good to me in Storybook. One thing, would it be possible to implement a test, which checks that the width of the checkbox is always as desired without mich effort?

**Comment by bar-tay** [comment]
@thrbnhrtmnn should this be an accessibility test which is shown in the tab storybook or a regular test in the code?

**Review by faselbaum — APPROVED** [review]

**Comment by thrbnhrtmnn** [comment]
> @thrbnhrtmnn should this be an accessibility test which is shown in the tab storybook or a regular test in the code?

No, this is not about a11y, it would be a regular test in code to decrease the chances of this bug happening again in the future.

**Comment by bar-tay** [comment]
@thrbnhrtmnn I don't think that's necessary, since I changed the width of the checkbox with a property which ensures that it   can't be any other size than the desired one.

**Pull request merged**
